Easy export logs via tool is added
includes:
	1. View menu to see the selected logs and desired output directory.
	2. Log menu to allow user to choose the logs to ve exported
	3. Output menu to allow user to choose the output directory for the exported logs
	4. Export function to export all the selected log file(s)
	5. Reset function to reset the log and output directory value
	6. Back function to return to the main menu

diff --git a/resources/usr/bin/scout-manage b/resources/usr/bin/scout-manage
--- a/resources/usr/bin/scout-manage
+++ b/resources/usr/bin/scout-manage
@@ -34,6 +34,8 @@ MAINMENU+=("SUPERVISE:Supervise or enable elevated commands from the container."
 MAINMENU+=("CHAT:Enter IRC chat with the expert.")
 MAINMENU+=("CONTAINER-SHELL:Start a root shell inside guest container.")
 MAINMENU+=("SHELL:Start a root local shell.")
+MAINMENU+=("EXPORT LOGS:Tool to export log files.")
+
 if ! ps -p $(ps -p "$$" -o "ppid=") -o cmd= | grep -q '\.service'
 then
  MAINMENU+=("EXIT:Return to previous environment.")
@@ -90,6 +92,16 @@ SUPERVISEMENU+=("ENABLE APPROVAL BYPASS:Use this in case of full trust to the ex
 SUPERVISEMENU+=("BACK:Return to previous menu.")
 unset T; T=("${SUPERVISORMENU[@]}"); unset SUPERVISORMENU; declare -a SUPERVISORMENU; for (( i=${#T[@]}-1; i>=0; i-- )); do SUPERVISORMENU[${#SUPERVISORMENU[@]}]=${T[i]}; done
 
+declare -a EXPORTLOGMENU
+EXPORTLOGMENU+=("VIEW:View all selected logs and export location.")
+EXPORTLOGMENU+=("LOGS:Select logs to be exported.")
+EXPORTLOGMENU+=("OUTPUT:Select export destination.")
+EXPORTLOGMENU+=("EXPORT:Begin to export.")
+EXPORTLOGMENU+=("RESET:Reset logs and output values.")
+EXPORTLOGMENU+=("BACK:Return to previous menu.")
+unset T; T=("${EXPORTLOGMENU[@]}"); unset EXPORTLOGMENU; declare -a EXPORTLOGMENU; for (( i=${#T[@]}-1; i>=0; i-- )); do EXPORTLOGMENU[${#EXPORTLOGMENU[@]}]=${T[i]}; done
+
+
 function dialog_menu()
 {
   DIALOGTITLE="$1"
@@ -120,6 +132,7 @@ function dialog_export()
 while true
 do
   dialog_export
+
   read MAINCHOICE <<< $(dialog_menu "MAIN MENU" "$MAINMENUTEXT" "$(declare -p MAINMENU)")
 
   case "$MAINCHOICE" in
@@ -586,6 +599,92 @@ Privileged mount mode is currently $PMSTATE.";
          fi
          continue;
          ;;
+     "EXPORT LOGS")
+         declare -a logChoice
+         outputDIrectory="null"
+         while true
+         do
+            dialog_export
+
+            read EXPORTLOGCHOICE <<< $(dialog_menu "EXPORT TOOL" "Tool to export logs generated by the system easily" "$(declare -p EXPORTLOGMENU)")
+
+            case "$EXPORTLOGCHOICE" in
+              "VIEW")
+                  if [ "VIEW" == "VIEW" ];
+                  then
+                      dialog --title "Export Tool View" --msgbox " $( echo "\n" ;echo "\n") -----LOG FILE CHOSEN----- $( echo "\n" ; echo "\n") $( [ -z $logChoice ] && echo "No log file was selected"; [ ! -z $logChoice ] &&  echo "${logChoice[@]}" | tr ' ' '\n' | awk -F'/' '{print $NF}' )  $( echo "\n"; echo "\n") -----OUTPUT DIRECTORY----- $( echo "\n"; echo "\n") $( if [ $outputDirectory == "null" ]; then echo "Directory output is not set." ; else echo "$outputDirectory";fi;) " $BOXHEIGHT $BOXWIDTH
+                  fi
+                  continue;
+                  ;;
+              "LOGS")
+                  if [ "LOGS" == "LOGS" ];
+                  then
+                      declare -a listOfLog
+                      option1=""
+                      [ -f /opt/container/history/log/supervised.log ] && option1="/opt/container/history/log/supervised.log"; [ ! -f /opt/container/history/log/supervised.log ] && option1="Not Available" ;
+                      
+                      logFiles=(dialog --separate-output --checklist "Select options:" $BOXHEIGHT $BOXWIDTH 44)
+                      options=("$option1" "(Supervised Shell log)" off   
+                              
+                              )
+                      choices=$("${logFiles[@]}" "${options[@]}" 3>&1 1>&2 2>&3)
+                  fi
+
+                  for choice in $choices
+                  do
+                    case $choice in
+                    "/opt/container/history/log/supervised.log")
+                    logChoice+=("/opt/container/history/log/supervised.log")
+                    ;;
+                    esac
+                  done
+
+                  continue;
+                  ;;
+
+              "OUTPUT")
+                  if [ "OUTPUT" == "OUTPUT" ];
+                  then
+                      outputDirectory=$(dialog --title "Select export directory target location" --fselect / $BOXHEIGHT $BOXWIDTH 3>&1 1>&2 2>&3)
+                      [ ! -d "$outputDirectory" ] && mkdir $outputDirectory;
+                  fi
+                  continue;
+                  ;;
+
+              "EXPORT")
+                  if [ "EXPORT" == "EXPORT" ];
+                  then
+                      [ -z $logChoice ] && dialog --title "Warning!" --msgbox 'Log file is not selected or invalid' $BOXHEIGHT $BOXWIDTH;
+                      [ ! -d $outputDirectory ] && dialog --title "Warning!" --msgbox 'Output directory is not selected or invalid' $BOXHEIGHT $BOXWIDTH;
+                      if [ ! -z $logChoice ] && [ -d $outputDirectory ];
+                      then
+                          for item in ${logChoice[@]};
+                          do
+                              cp $item $outputDirectory
+                          done
+                          dialog --title "Status" --msgbox 'All log files is exported successfully' $BOXHEIGHT $BOXWIDTH;
+                      fi
+                  fi
+                  continue;
+                  ;;
+
+              "RESET")
+                  if [ "RESET" == "RESET" ]
+                  then
+                      unset logChoice; outputDirectory="null"; dialog --title "Task status" --msgbox 'Log and output Directory options is reseted succesfully!' $BOXHEIGHT $BOXWIDTH;
+                  fi
+                  continue;
+                  ;;
+
+              "BACK")
+                  break;
+                  ;;
+            esac
+
+         done
+         continue;
+         ;;
+
 
     "SUPERVISE")
   while true
@@ -641,5 +740,7 @@ Privileged mount mode is currently $PMSTATE.";
                 ;;
          esac
        done
+   
   esac
 done
+
