Minor bugfix

diff --git a/scripts/functions b/scripts/functions
--- a/scripts/functions
+++ b/scripts/functions
@@ -102,12 +102,6 @@ packinitrd()
 install_required_package()
 {
   PKGNAME="$1"
-  if [ -z "$APT_UPDATED" -o "$APT_UPDATED" != "1" ]
-  then
-    sudo apt -y update
-    export APT_UPDATED="1"
-  fi
-
   if ! dpkg-query --show --showformat='${db:Status-Status}\n' $PKGNAME | grep -q "^installed$"
   then
     statusprint "$PKGNAME was not found your system. It is required to continue.\nPlease authorize installing $PKGNAME.."
@@ -120,9 +114,18 @@ install_required_package()
         statusprint "Enabling additional repository ($REPOSITORY) for your system.."
         OSCODENAME=`lsb_release -c| awk '{print $2}'`
         sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ $OSCODENAME $REPOSITORY"
+        sudo apt -y update
       fi
     fi;
-    if ! sudo apt -y install "$PKGNAME"; then exit 1; fi;
+    if ! sudo apt -y install "$PKGNAME"; 
+    then 
+      sudo apt -y update
+      if ! sudo apt -y install "$PKGNAME"; 
+      then 
+        statusprint "ERROR: Couldn't install/find $PKGNAME. Aborting.."
+        exit 1;
+      fi;
+    fi;
   fi
 }
 
